name: flutter_temp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # firebase
  firebase_core: ^2.7.1
  firebase_remote_config: ^3.0.14
  firebase_analytics: ^10.1.5
  firebase_crashlytics: ^3.0.16

  # api
  http: ^0.13.5

  # localize
  # localize_and_translate: ^4.1.1
  flutter_translate: ^4.0.3
  flutter_localization: ^0.1.10
  flutter_localizations: 
    sdk: flutter
  # state management
  provider: ^6.0.5
  # local storage
  hive: ^2.2.3
  path_provider: ^2.0.13
  # 
  loader_overlay: ^2.1.0
  flutter_screenutil: ^5.7.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/langs/
    - assets/langs/vi.json
    - assets/langs/en.json