// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsoLlORuZye0pjr1uHKs8TRUbzZ3dBDik',
    appId: '1:256307979251:android:a0be1468a56878bf1c6886',
    messagingSenderId: '256307979251',
    projectId: 'demoproject-68652',
    databaseURL: 'https://demoproject-68652-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoproject-68652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6IbX0hD8kPzsTa_BYoofQPX0DnfPc4c',
    appId: '1:256307979251:ios:3dff1963daa0680a1c6886',
    messagingSenderId: '256307979251',
    projectId: 'demoproject-68652',
    databaseURL: 'https://demoproject-68652-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoproject-68652.appspot.com',
    androidClientId: '256307979251-2necel15n4579934v2use8g40eagrt2s.apps.googleusercontent.com',
    iosClientId: '256307979251-0f0pm6gjg03dbhvpjlrge1n7thn5kjf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tempApp',
  );
}
